
Carbon:
  IncludeAssets:
    Packages:
      aa_Theme:
        Path:
          Inline:
            CSS: 'Public/Frontend'
            JS: 'Public/Frontend'
          File:
            CSS: 'Public/Frontend'
            JS: 'Public/Frontend'
        # Asset files who get's loaded in live and backend view
        General:
          Head:
            - index.css
          Body:
            - index.js
